save_path: /home

board: rb5

rtsp_stream_url: rtsp://127.0.0.1:8900/live
video_format: video/x-raw
codec: h265
image_width: 1280
image_height: 720

siyi_camera_ip: 192.168.50.25
siyi_camera_port: 37260
